name: "Sshd Cloudflared"
description: 'Debuging Action using ssh'
runs:
  using: "composite"
  steps:
    - run: ls -lAh ${GITHUB_ACTION_PATH}
      shell: bash
    - run: ./setup-ssh
      shell: bash
