name: "Sshd Cloudflared"
description: 'Debuging Action using ssh'
runs:
  using: "composite"
  steps:
    - run: chmod +x ${GITHUB_WORKSPACE}/setup-ssh
      shell: bash
    - run: ./${GITHUB_WORKSPACE}/setup-ssh
      shell: bash
