name: "Sshd Cloudflared"
description: 'Debuging Action using ssh'
runs:
  using: "composite"
  steps:
    - run: chmod +x ${GITHUB_ACTION_PATH}/setup-ssh
      shell: bash
    - run: ${GITHUB_ACTION_PATH}/setup-ssh
      shell: bash
